.nh
.TH "gh" "1" "Jun 2021" "" ""

.SH NAME
.PP
gh\-pr\-status \- Show status of relevant pull requests


.SH SYNOPSIS
.PP
\fBgh pr status [flags]\fP


.SH DESCRIPTION
.PP
Show status of relevant pull requests


.SH OPTIONS
.PP
\fB\-q\fP, \fB\-\-jq\fP=""
	Filter JSON output using a jq \fB\fCexpression\fR

.PP
\fB\-\-json\fP=[]
	Output JSON with the specified \fB\fCfields\fR

.PP
\fB\-t\fP, \fB\-\-template\fP=""
	Format JSON output using a Go template


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-pr(1)\fP
