.nh
.TH "gh" "1" "Jun 2021" "" ""

.SH NAME
.PP
gh\-run\-view \- View a summary of a workflow run


.SH SYNOPSIS
.PP
\fBgh run view [] [flags]\fP


.SH DESCRIPTION
.PP
View a summary of a workflow run


.SH OPTIONS
.PP
\fB\-\-exit\-status\fP[=false]
	Exit with non\-zero status if run failed

.PP
\fB\-j\fP, \fB\-\-job\fP=""
	View a specific job ID from a run

.PP
\fB\-\-log\fP[=false]
	View full log for either a run or specific job

.PP
\fB\-\-log\-failed\fP[=false]
	View the log for any failed steps in a run or specific job

.PP
\fB\-v\fP, \fB\-\-verbose\fP[=false]
	Show job steps

.PP
\fB\-w\fP, \fB\-\-web\fP[=false]
	Open run in the browser


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH EXAMPLE
.PP
.RS

.nf
# Interactively select a run to view, optionally selecting a single job
$ gh run view

# View a specific run
$ gh run view 12345

# View a specific job within a run
$ gh run view \-\-job 456789

# View the full log for a specific job
$ gh run view \-\-log \-\-job 456789

# Exit non\-zero if a run failed
$ gh run view 0451 \-\-exit\-status \&\& echo "run pending or passed"


.fi
.RE


.SH SEE ALSO
.PP
\fBgh\-run(1)\fP
