.nh
.TH "gh" "1" "Jun 2021" "" ""

.SH NAME
.PP
gh\-run \- View details about workflow runs


.SH SYNOPSIS
.PP
\fBgh run  [flags]\fP


.SH DESCRIPTION
.PP
List, view, and watch recent workflow runs from GitHub Actions.


.SH OPTIONS
.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh(1)\fP, \fBgh\-run\-download(1)\fP, \fBgh\-run\-list(1)\fP, \fBgh\-run\-rerun(1)\fP, \fBgh\-run\-view(1)\fP, \fBgh\-run\-watch(1)\fP
