.nh
.TH "gh" "1" "Jun 2021" "" ""

.SH NAME
.PP
gh\-secret\-set \- Create or update secrets


.SH SYNOPSIS
.PP
\fBgh secret set  [flags]\fP


.SH DESCRIPTION
.PP
Locally encrypt a new or updated secret at either the repository, environment, or organization level and send it to GitHub for storage.


.SH OPTIONS
.PP
\fB\-b\fP, \fB\-\-body\fP=""
	A value for the secret. Reads from STDIN if not specified.

.PP
\fB\-e\fP, \fB\-\-env\fP=""
	Set a secret for an organization

.PP
\fB\-o\fP, \fB\-\-org\fP=""
	Set a secret for an organization

.PP
\fB\-r\fP, \fB\-\-repos\fP=[]
	List of repository names for \fB\fCselected\fR visibility

.PP
\fB\-v\fP, \fB\-\-visibility\fP="private"
	Set visibility for an organization secret: \fB\fCall\fR, \fB\fCprivate\fR, or \fB\fCselected\fR


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH EXAMPLE
.PP
.RS

.nf
Paste secret in prompt
$ gh secret set MYSECRET

Use environment variable as secret value
$ gh secret set MYSECRET  \-b"${ENV\_VALUE}"

Use file as secret value
$ gh secret set MYSECRET < file.json

Set environment level secret
$ gh secret set MYSECRET \-bval \-\-env=anEnv

Set organization level secret visible to entire organization
$ gh secret set MYSECRET \-bval \-\-org=anOrg \-\-visibility=all

Set organization level secret visible only to certain repositories
$ gh secret set MYSECRET \-bval \-\-org=anOrg \-\-repos="repo1,repo2,repo3"


.fi
.RE


.SH SEE ALSO
.PP
\fBgh\-secret(1)\fP
