.nh
.TH "gh" "1" "Jun 2021" "" ""

.SH NAME
.PP
gh\-workflow \- View details about GitHub Actions workflows


.SH SYNOPSIS
.PP
\fBgh workflow  [flags]\fP


.SH DESCRIPTION
.PP
List, view, and run workflows in GitHub Actions.


.SH OPTIONS
.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh(1)\fP, \fBgh\-workflow\-disable(1)\fP, \fBgh\-workflow\-enable(1)\fP, \fBgh\-workflow\-list(1)\fP, \fBgh\-workflow\-run(1)\fP, \fBgh\-workflow\-view(1)\fP
