.nh
.TH "gh" "1" "Jun 2021" "" ""

.SH NAME
.PP
gh\-workflow\-list \- List workflows


.SH SYNOPSIS
.PP
\fBgh workflow list [flags]\fP


.SH DESCRIPTION
.PP
List workflow files, hiding disabled workflows by default.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-all\fP[=false]
	Show all workflows, including disabled workflows

.PP
\fB\-L\fP, \fB\-\-limit\fP=50
	Maximum number of workflows to fetch


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-workflow(1)\fP
