.nh
.TH "gh" "1" "Jun 2021" "" ""

.SH NAME
.PP
gh\-workflow\-disable \- Disable a workflow


.SH SYNOPSIS
.PP
\fBgh workflow disable [ | ] [flags]\fP


.SH DESCRIPTION
.PP
Disable a workflow, preventing it from running or showing up when listing workflows.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command

.PP
\fB\-R\fP, \fB\-\-repo\fP=""
	Select another repository using the \fB\fC[HOST/]OWNER/REPO\fR format


.SH SEE ALSO
.PP
\fBgh\-workflow(1)\fP
